server:
  port: 19014
##################################################################
spring:
  servlet:
    #上传文件配置
    multipart:
      #启用 http上传处理
      enabled: true
      #最大上传大小1G【默认1M】 -1不限制大小
      max-file-size: -1
      max-request-size: -1