# application.yml 编码是 UTF-8
#####################################################################
server:
  # 该项目启动的端口号
  port: 18080
  # 服务配置
  servlet:
    # 服务路径
    context-path: /sb
#####################################################################
